#!/bin/bash

MODULE="module.project-factory"
NEW_MODULE="module.project-factory.module.project-factory"

terraform state mv $MODULE.random_id.random_project_id_suffix $NEW_MODULE.random_id.random_project_id_suffix
terraform state mv $MODULE.google_project.project $NEW_MODULE.google_project.project
terraform state mv $MODULE.google_project_service.project_services $NEW_MODULE.google_project_service.project_services
terraform state mv $MODULE.google_compute_shared_vpc_service_project.shared_vpc_attachment $MODULE.google_compute_shared_vpc_service_project.shared_vpc_attachment
terraform state mv $MODULE.null_resource.delete_default_compute_service_account $NEW_MODULE.null_resource.delete_default_compute_service_account
terraform state mv $MODULE.google_service_account.default_service_account $NEW_MODULE.google_service_account.default_service_account
terraform state mv $MODULE.google_project_iam_member.default_service_account_membership $NEW_MODULE.google_project_iam_member.default_service_account_membership
terraform state mv $MODULE.google_project_iam_member.gsuite_group_role $NEW_MODULE.google_project_iam_member.gsuite_group_role
terraform state mv $MODULE.google_service_account_iam_member.service_account_grant_to_group $NEW_MODULE.google_service_account_iam_member.service_account_grant_to_group
terraform state mv $MODULE.google_project_iam_member.controlling_group_vpc_membership $NEW_MODULE.$MODULE.google_project_iam_member.controlling_group_vpc_membership
terraform state mv $MODULE.google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets $NEW_MODULE.google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets
terraform state mv $MODULE.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets $NEW_MODULE.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets
terraform state mv $MODULE.google_compute_subnetwork_iam_member.apis_service_account_role_to_vpc_subnets $NEW_MODULE.google_compute_subnetwork_iam_member.apis_service_account_role_to_vpc_subnets
terraform state mv $MODULE.google_project_usage_export_bucket.usage_report_export $NEW_MODULE.google_project_usage_export_bucket.usage_report_export
terraform state mv $MODULE.google_storage_bucket.project_bucket $NEW_MODULE.google_storage_bucket.project_bucket
terraform state mv $MODULE.google_storage_bucket_iam_member.group_storage_admin_on_project_bucket $NEW_MODULE.google_storage_bucket_iam_member.group_storage_admin_on_project_bucket
terraform state mv $MODULE.google_storage_bucket_iam_member.s_account_storage_admin_on_project_bucket $NEW_MODULE.google_storage_bucket_iam_member.s_account_storage_admin_on_project_bucket
terraform state mv $MODULE.google_storage_bucket_iam_member.api_s_account_storage_admin_on_project_bucket $NEW_MODULE.google_storage_bucket_iam_member.api_s_account_storage_admin_on_project_bucket
terraform state mv $MODULE.google_compute_subnetwork_iam_member.gke_shared_vpc_subnets $NEW_MODULE.google_compute_subnetwork_iam_member.gke_shared_vpc_subnets
terraform state mv $MODULE.google_project_iam_member.gke_host_agent $NEW_MODULE.google_project_iam_member.gke_host_agent 
